[
    'APP_OPEN_FILE',
    'APP_CLOSE_FILE',
    'APP_SAVE_FILE',
    'FILETREE_SELECT_ITEM',
    'FILETREE_EXPAND_ITEM',
    'FILETREE_COLLAPSE_ITEM',
    'FILETREE_TOGGLE_ITEM'
].forEach(x => exports[x] = x);
