module.exports = {
    FILETREE_SELECT_ITEM   : 'FILETREE_SELECT_ITEM',
    FILETREE_EXPAND_ITEM   : 'FILETREE_EXPAND_ITEM',
    FILETREE_COLLAPSE_ITEM : 'FILETREE_COLLAPSE_ITEM',
    FILETREE_TOGGLE_ITEM   : 'FILETREE_TOGGLE_ITEM',
    FILETREE_REVEAL_PATH   : 'FILETREE_REVEAL_PATH'
};
